// AUTO-GENERATED by backend/scripts/generate_ts_types.py — DO NOT EDIT
// Re-run the generator any time backend/app/schemas/ changes.

export type SourceType = 'internal_db' | 'web' | 'inferred' | 'scraped';

export type MessageRole = 'user' | 'assistant' | 'system' | 'tool';

export interface Ingredient {
  id: string;
  name: string;
  canonical_name?: string | null;
  company_id: string;
  sku?: string | null;
}

export interface Supplier {
  id: string;
  name: string;
  certifications: string[];
  lead_time_days?: number | null;
  moq?: number | null;
  country?: string | null;
}

export interface ConsolidationGroup {
  id: string;
  canonical_name: string;
  ingredient_ids: string[];
  supplier_count: number;
  fragmentation_score: number;
  company_ids: string[];
}

export interface EvidenceItem {
  claim: string;
  source_url?: string | null;
  source_type: 'internal_db' | 'web' | 'inferred' | 'scraped';
  confidence: number;
  snippet?: string | null;
}

export interface EvidenceBundle {
  items: EvidenceItem[];
  summary: string;
}

export interface Message {
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  tool_call_id?: string | null;
}

export interface ComplianceInput {
  ingredient_id: string;
  requirements: string[];
}

export interface ComplianceResult {
  pass: boolean;
  requirements: string[];
  evidence: EvidenceBundle;
}

export interface ChatRequest {
  messages: Message[];
  session_id: string;
}

export interface TextEvent       { type: 'text';        content: string; }
export interface ToolCallEvent   { type: 'tool_call';   name: string; args: unknown; }
export interface ToolResultEvent { type: 'tool_result'; name: string; result: unknown; }
export interface EvidenceEvent   { type: 'evidence';    items: EvidenceItem[]; }
export interface TraceEvent      { type: 'trace';       agent?: string | null; step: string; }
export interface DoneEvent       { type: 'done'; }

export type ChatEvent =
  | TextEvent
  | ToolCallEvent
  | ToolResultEvent
  | EvidenceEvent
  | TraceEvent
  | DoneEvent;
