// Facade over `./types.generated` (auto-generated by `yarn gen:types` from
// the backend's /openapi.json). REST types are re-exported with clean names
// so consumers can `import { Ingredient } from '@/lib/types'` instead of
// digging into `components['schemas']['Ingredient']`.

import type { components } from './types.generated';

type S = components['schemas'];

export type Ingredient = S['Ingredient'];
