// Facade over `./types.generated` (auto-generated by `npm run gen:types` from
// the backend's /openapi.json) + hand-written SSE event types below.
//
// REST types are re-exported with clean names so consumers can
// `import { Ingredient } from '@/lib/types'` instead of digging into
// `components['schemas']['Ingredient']`.

import type { components } from './types.generated';

type S = components['schemas'];

export type Ingredient = S['Ingredient'];
export type Supplier = S['Supplier'];
export type ConsolidationGroup = S['ConsolidationGroup'];
export type EvidenceItem = S['EvidenceItem'];
export type EvidenceBundle = S['EvidenceBundle'];
export type Message = S['Message'];
export type ComplianceInput = S['ComplianceInput'];
export type ComplianceResult = S['ComplianceResult'];
export type ChatRequest = S['ChatRequest'];

// Literal-string aliases are inlined by openapi-typescript (they appear as
// enum fields, not as standalone schemas), so derive them from the fields.
export type SourceType = EvidenceItem['source_type'];
export type MessageRole = Message['role'];

// ---------------------------------------------------------------------------
// SSE event types — NOT in OpenAPI (FastAPI does not describe SSE payloads),
// so these are maintained by hand. If the backend adds a new ChatEvent
// variant in `app/schemas/chat.py`, mirror it here.
// ---------------------------------------------------------------------------

export interface TextEvent       { type: 'text';        content: string; }
export interface ToolCallEvent   { type: 'tool_call';   name: string; args: unknown; }
export interface ToolResultEvent { type: 'tool_result'; name: string; result: unknown; }
export interface EvidenceEvent   { type: 'evidence';    items: EvidenceItem[]; }
export interface TraceEvent      { type: 'trace';       agent?: string | null; step: string; }
export interface DoneEvent       { type: 'done'; }

export type ChatEvent =
  | TextEvent
  | ToolCallEvent
  | ToolResultEvent
  | EvidenceEvent
  | TraceEvent
  | DoneEvent;
